function getTopLevelDiffTagLogicConfig( maxLevelId )

	local TopLevelDiffTagLogicConfig = {}

	TopLevelDiffTagLogicConfig.maxLevelId = maxLevelId

	TopLevelDiffTagLogicConfig.V4 = {

		[1] = {
			minLevel = 0 ,
			maxLevel = 400 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 3 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 3 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 5 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 7 ,
				} ,
				[2] = {
					mixDiff = 4 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 4 ,
					diff_2_type = "count" ,
					diff_2_value = 5 ,
					diff_3_type = "count" ,
					diff_3_value = 6 ,
					diff_4_type = "count" ,
					diff_4_value = 8 ,
					diff_5_type = "count" ,
					diff_5_value = 10 ,
				} ,
				
			} ,
		} ,

		[2] = {
			minLevel = 401 ,
			maxLevel = 800 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 4 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 3 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 4 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 5 ,
				} ,
				[2] = {
					mixDiff = 5 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 5 ,
					diff_2_type = "count" ,
					diff_2_value = 6 ,
					diff_3_type = "count" ,
					diff_3_value = 8 ,
					diff_4_type = "count" ,
					diff_4_value = 10 ,
					diff_5_type = "count" ,
					diff_5_value = 12 ,
				} ,
				
			} ,
		} ,

		[3] = {
			minLevel = 801 ,
			maxLevel = 1200 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 5 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 4 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 7 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 10 ,
				} ,
				[2] = {
					mixDiff = 6 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 6 ,
					diff_2_type = "count" ,
					diff_2_value = 7 ,
					diff_3_type = "count" ,
					diff_3_value = 9 ,
					diff_4_type = "count" ,
					diff_4_value = 12 ,
					diff_5_type = "count" ,
					diff_5_value = 15 ,
				} ,
				
			} ,
		} ,

		[4] = {
			minLevel = 1201 ,
			maxLevel = 1600 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 6 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 4 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 7 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 10 ,
				} ,
				[2] = {
					mixDiff = 7 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 7 ,
					diff_2_type = "count" ,
					diff_2_value = 8 ,
					diff_3_type = "count" ,
					diff_3_value = 10 ,
					diff_4_type = "count" ,
					diff_4_value = 13 ,
					diff_5_type = "count" ,
					diff_5_value = 16 ,
				} ,
				
			} ,
		} ,

		[5] = {
			minLevel = 1601 ,
			maxLevel = tonumber( TopLevelDiffTagLogicConfig.maxLevelId - 60) ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 8 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 4 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 7 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 10 ,
				} ,
				[2] = {
					mixDiff = 9 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 9 ,
					diff_2_type = "count" ,
					diff_2_value = 10 ,
					diff_3_type = "count" ,
					diff_3_value = 12 ,
					diff_4_type = "count" ,
					diff_4_value = 15 ,
					diff_5_type = "count" ,
					diff_5_value = 18 ,
				} ,
				
			} ,
		} ,

		[6] = {
			minLevel = tonumber( TopLevelDiffTagLogicConfig.maxLevelId - 60 + 1) ,
			maxLevel = TopLevelDiffTagLogicConfig.maxLevelId  ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 10 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 3 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 4 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 6 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 10 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 15 ,
				} ,
				[2] = {
					mixDiff = 11 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 13 ,
					diff_2_type = "count" ,
					diff_2_value = 14 ,
					diff_3_type = "count" ,
					diff_3_value = 16 ,
					diff_4_type = "count" ,
					diff_4_value = 20 ,
					diff_5_type = "count" ,
					diff_5_value = 25 ,
				} ,
				
			} ,
		} ,
	}



	----------------------------------------------------------------------------------------------



	TopLevelDiffTagLogicConfig.V5 = {
		[1] = {
			minLevel = 0 ,
			maxLevel = 100 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 1 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 3 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 4 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 5 ,
				} ,
				[2] = {
					mixDiff = 2 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 1 ,
					diff_2_type = "count" ,
					diff_2_value = 2 ,
					diff_3_type = "count" ,
					diff_3_value = 3 ,
					diff_4_type = "count" ,
					diff_4_value = 4 ,
					diff_5_type = "count" ,
					diff_5_value = 5 ,
				} ,
				
			} ,
		} ,

		[2] = {
			minLevel = 101 ,
			maxLevel = 200 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 1 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 3 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 4 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 5 ,
				} ,
				[2] = {
					mixDiff = 2 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 2 ,
					diff_2_type = "count" ,
					diff_2_value = 3 ,
					diff_3_type = "count" ,
					diff_3_value = 4 ,
					diff_4_type = "count" ,
					diff_4_value = 5 ,
					diff_5_type = "count" ,
					diff_5_value = 6 ,
				} ,
				
			} ,
		} ,

		[3] = {
			minLevel = 201 ,
			maxLevel = 300 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 2 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 3 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 4 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 5 ,
				} ,
				[2] = {
					mixDiff = 3 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 2 ,
					diff_2_type = "count" ,
					diff_2_value = 3 ,
					diff_3_type = "count" ,
					diff_3_value = 4 ,
					diff_4_type = "count" ,
					diff_4_value = 5 ,
					diff_5_type = "count" ,
					diff_5_value = 6 ,
				} ,
				
			} ,
		} ,

		[4] = {
			minLevel = 301 ,
			maxLevel = 400 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 2 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 3 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 4 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 5 ,
				} ,
				[2] = {
					mixDiff = 3 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 2 ,
					diff_2_type = "count" ,
					diff_2_value = 3 ,
					diff_3_type = "count" ,
					diff_3_value = 4 ,
					diff_4_type = "count" ,
					diff_4_value = 5 ,
					diff_5_type = "count" ,
					diff_5_value = 6 ,
				} ,
				
			} ,
		} ,

		[5] = {
			minLevel = 401 ,
			maxLevel = 500 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 2 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 3 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 5 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 7 ,
				} ,
				[2] = {
					mixDiff = 3 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 3 ,
					diff_2_type = "count" ,
					diff_2_value = 4 ,
					diff_3_type = "count" ,
					diff_3_value = 5 ,
					diff_4_type = "count" ,
					diff_4_value = 6 ,
					diff_5_type = "count" ,
					diff_5_value = 7 ,
				} ,
				
			} ,
		} ,

		[6] = {
			minLevel = 501 ,
			maxLevel = 800 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 4 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 3 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 4 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 5 ,
				} ,
				[2] = {
					mixDiff = 5 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 5 ,
					diff_2_type = "count" ,
					diff_2_value = 6 ,
					diff_3_type = "count" ,
					diff_3_value = 8 ,
					diff_4_type = "count" ,
					diff_4_value = 10 ,
					diff_5_type = "count" ,
					diff_5_value = 12 ,
				} ,
				
			} ,
		} ,

		[7] = {
			minLevel = 801 ,
			maxLevel = 1200 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 5 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 4 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 7 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 10 ,
				} ,
				[2] = {
					mixDiff = 6 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 6 ,
					diff_2_type = "count" ,
					diff_2_value = 7 ,
					diff_3_type = "count" ,
					diff_3_value = 9 ,
					diff_4_type = "count" ,
					diff_4_value = 12 ,
					diff_5_type = "count" ,
					diff_5_value = 15 ,
				} ,
				
			} ,
		} ,

		[8] = {
			minLevel = 1201 ,
			maxLevel = 1600 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 6 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 4 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 7 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 10 ,
				} ,
				[2] = {
					mixDiff = 7 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 7 ,
					diff_2_type = "count" ,
					diff_2_value = 8 ,
					diff_3_type = "count" ,
					diff_3_value = 10 ,
					diff_4_type = "count" ,
					diff_4_value = 13 ,
					diff_5_type = "count" ,
					diff_5_value = 16 ,
				} ,
				
			} ,
		} ,

		[9] = {
			minLevel = 1601 ,
			maxLevel = tonumber( TopLevelDiffTagLogicConfig.maxLevelId - 60) ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 8 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 4 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 7 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 10 ,
				} ,
				[2] = {
					mixDiff = 9 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 9 ,
					diff_2_type = "count" ,
					diff_2_value = 10 ,
					diff_3_type = "count" ,
					diff_3_value = 12 ,
					diff_4_type = "count" ,
					diff_4_value = 15 ,
					diff_5_type = "count" ,
					diff_5_value = 18 ,
				} ,
				
			} ,
		} ,

		[10] = {
			minLevel = tonumber( TopLevelDiffTagLogicConfig.maxLevelId - 60 + 1) ,
			maxLevel = TopLevelDiffTagLogicConfig.maxLevelId ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 10 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 3 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 4 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 6 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 10 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 15 ,
				} ,
				[2] = {
					mixDiff = 11 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 13 ,
					diff_2_type = "count" ,
					diff_2_value = 14 ,
					diff_3_type = "count" ,
					diff_3_value = 16 ,
					diff_4_type = "count" ,
					diff_4_value = 20 ,
					diff_5_type = "count" ,
					diff_5_value = 25 ,
				} ,
				
			} ,
		} ,
	}



	----------------------------------------------------------------------------------------------



	TopLevelDiffTagLogicConfig.V6 = {

		[1] = {
			minLevel = 0 ,
			maxLevel = 100 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 1 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 3 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 4 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 5 ,
				} ,
				[2] = {
					mixDiff = 2 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 1 ,
					diff_2_type = "count" ,
					diff_2_value = 2 ,
					diff_3_type = "count" ,
					diff_3_value = 3 ,
					diff_4_type = "count" ,
					diff_4_value = 4 ,
					diff_5_type = "count" ,
					diff_5_value = 5 ,
				} ,
				
			} ,
		} ,

		[2] = {
			minLevel = 101 ,
			maxLevel = 200 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 1 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 3 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 4 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 5 ,
				} ,
				[2] = {
					mixDiff = 2 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 2 ,
					diff_2_type = "count" ,
					diff_2_value = 3 ,
					diff_3_type = "count" ,
					diff_3_value = 4 ,
					diff_4_type = "count" ,
					diff_4_value = 5 ,
					diff_5_type = "count" ,
					diff_5_value = 6 ,
				} ,
				
			} ,
		} ,

		[3] = {
			minLevel = 201 ,
			maxLevel = 300 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 2 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 3 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 4 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 5 ,
				} ,
				[2] = {
					mixDiff = 3 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 2 ,
					diff_2_type = "count" ,
					diff_2_value = 3 ,
					diff_3_type = "count" ,
					diff_3_value = 4 ,
					diff_4_type = "count" ,
					diff_4_value = 5 ,
					diff_5_type = "count" ,
					diff_5_value = 6 ,
				} ,
				
			} ,
		} ,

		[4] = {
			minLevel = 301 ,
			maxLevel = 400 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 2 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 3 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 4 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 5 ,
				} ,
				[2] = {
					mixDiff = 3 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 2 ,
					diff_2_type = "count" ,
					diff_2_value = 3 ,
					diff_3_type = "count" ,
					diff_3_value = 4 ,
					diff_4_type = "count" ,
					diff_4_value = 5 ,
					diff_5_type = "count" ,
					diff_5_value = 6 ,
				} ,
				
			} ,
		} ,

		[5] = {
			minLevel = 401 ,
			maxLevel = 500 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 2 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 3 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 5 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 7 ,
				} ,
				[2] = {
					mixDiff = 3 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 3 ,
					diff_2_type = "count" ,
					diff_2_value = 4 ,
					diff_3_type = "count" ,
					diff_3_value = 5 ,
					diff_4_type = "count" ,
					diff_4_value = 6 ,
					diff_5_type = "count" ,
					diff_5_value = 7 ,
				} ,
				
			} ,
		} ,

		[6] = {
			minLevel = 501 ,
			maxLevel = 600 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 3 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 3 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 4 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 5 ,
				} ,
				[2] = {
					mixDiff = 4 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 4 ,
					diff_2_type = "count" ,
					diff_2_value = 5 ,
					diff_3_type = "count" ,
					diff_3_value = 6 ,
					diff_4_type = "count" ,
					diff_4_value = 7 ,
					diff_5_type = "count" ,
					diff_5_value = 8 ,
				} ,
				
			} ,
		} ,

		[7] = {
			minLevel = 601 ,
			maxLevel = 700 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 3 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 3 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 4 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 5 ,
				} ,
				[2] = {
					mixDiff = 4 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 4 ,
					diff_2_type = "count" ,
					diff_2_value = 5 ,
					diff_3_type = "count" ,
					diff_3_value = 6 ,
					diff_4_type = "count" ,
					diff_4_value = 7 ,
					diff_5_type = "count" ,
					diff_5_value = 8 ,
				} ,
				
			} ,
		} ,

		[8] = {
			minLevel = 701 ,
			maxLevel = 800 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 4 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 3 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 4 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 5 ,
				} ,
				[2] = {
					mixDiff = 5 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 5 ,
					diff_2_type = "count" ,
					diff_2_value = 6 ,
					diff_3_type = "count" ,
					diff_3_value = 7 ,
					diff_4_type = "count" ,
					diff_4_value = 8 ,
					diff_5_type = "count" ,
					diff_5_value = 9 ,
				} ,
				
			} ,
		} ,

		[9] = {
			minLevel = 801 ,
			maxLevel = 900 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 4 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 3 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 4 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 5 ,
				} ,
				[2] = {
					mixDiff = 5 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 5 ,
					diff_2_type = "count" ,
					diff_2_value = 6 ,
					diff_3_type = "count" ,
					diff_3_value = 7 ,
					diff_4_type = "count" ,
					diff_4_value = 8 ,
					diff_5_type = "count" ,
					diff_5_value = 9 ,
				} ,
				
			} ,
		} ,

		[10] = {
			minLevel = 901 ,
			maxLevel = 1000 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 4 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 3 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 4 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 5 ,
				} ,
				[2] = {
					mixDiff = 5 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 5 ,
					diff_2_type = "count" ,
					diff_2_value = 6 ,
					diff_3_type = "count" ,
					diff_3_value = 7 ,
					diff_4_type = "count" ,
					diff_4_value = 8 ,
					diff_5_type = "count" ,
					diff_5_value = 9 ,
				} ,
				
			} ,
		} ,

		[11] = {
			minLevel = 1001 ,
			maxLevel = 1100 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 4 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 3 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 4 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 5 ,
				} ,
				[2] = {
					mixDiff = 5 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 5 ,
					diff_2_type = "count" ,
					diff_2_value = 6 ,
					diff_3_type = "count" ,
					diff_3_value = 7 ,
					diff_4_type = "count" ,
					diff_4_value = 8 ,
					diff_5_type = "count" ,
					diff_5_value = 9 ,
				} ,
				
			} ,
		} ,

		[12] = {
			minLevel = 1101 ,
			maxLevel = 1200 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 4 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 3 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 4 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 5 ,
				} ,
				[2] = {
					mixDiff = 5 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 6 ,
					diff_2_type = "count" ,
					diff_2_value = 7 ,
					diff_3_type = "count" ,
					diff_3_value = 8 ,
					diff_4_type = "count" ,
					diff_4_value = 9 ,
					diff_5_type = "count" ,
					diff_5_value = 10 ,
				} ,
				
			} ,
		} ,

		[13] = {
			minLevel = 1201 ,
			maxLevel = 1600 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 6 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 4 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 7 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 10 ,
				} ,
				[2] = {
					mixDiff = 7 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 7 ,
					diff_2_type = "count" ,
					diff_2_value = 8 ,
					diff_3_type = "count" ,
					diff_3_value = 10 ,
					diff_4_type = "count" ,
					diff_4_value = 13 ,
					diff_5_type = "count" ,
					diff_5_value = 16 ,
				} ,
				
			} ,
		} ,

		[14] = {
			minLevel = 1601 ,
			maxLevel = tonumber( TopLevelDiffTagLogicConfig.maxLevelId - 60) ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 8 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 4 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 7 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 10 ,
				} ,
				[2] = {
					mixDiff = 9 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 9 ,
					diff_2_type = "count" ,
					diff_2_value = 10 ,
					diff_3_type = "count" ,
					diff_3_value = 12 ,
					diff_4_type = "count" ,
					diff_4_value = 15 ,
					diff_5_type = "count" ,
					diff_5_value = 18 ,
				} ,
				
			} ,
		} ,

		[15] = {
			minLevel = tonumber( TopLevelDiffTagLogicConfig.maxLevelId - 60 + 1) ,
			maxLevel = TopLevelDiffTagLogicConfig.maxLevelId ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 10 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 3 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 4 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 6 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 10 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 15 ,
				} ,
				[2] = {
					mixDiff = 11 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 13 ,
					diff_2_type = "count" ,
					diff_2_value = 14 ,
					diff_3_type = "count" ,
					diff_3_value = 16 ,
					diff_4_type = "count" ,
					diff_4_value = 20 ,
					diff_5_type = "count" ,
					diff_5_value = 25 ,
				} ,
				
			} ,
		} ,
	}


----------------------------------------------------------------------------------------------
	TopLevelDiffTagLogicConfig.V7 = {

		[1] = {
			minLevel = 0 ,
			maxLevel = 100 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 1 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 3 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 4 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 5 ,
				} ,
				[2] = {
					mixDiff = 2 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 1 ,
					diff_2_type = "count" ,
					diff_2_value = 2 ,
					diff_3_type = "count" ,
					diff_3_value = 3 ,
					diff_4_type = "count" ,
					diff_4_value = 4 ,
					diff_5_type = "count" ,
					diff_5_value = 5 ,
				} ,
				
			} ,
		} ,

		[2] = {
			minLevel = 101 ,
			maxLevel = 400 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 0 ,
					diff_2_type = "count" ,
					diff_2_value = 9999 ,
					diff_3_type = "count" ,
					diff_3_value = 1 ,
					diff_4_type = "count" ,
					diff_4_value = 9999 ,
					diff_5_type = "count" ,
					diff_5_value = 2 ,
				} ,
				
			} ,
		} ,

		[3] = {
			minLevel = 401 ,
			maxLevel = 800 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 1 ,
					diff_2_type = "count" ,
					diff_2_value = 9999 ,
					diff_3_type = "count" ,
					diff_3_value = 2 ,
					diff_4_type = "count" ,
					diff_4_value = 3 ,
					diff_5_type = "count" ,
					diff_5_value = 4 ,
				} ,
				
			} ,
		} ,

		[4] = {
			minLevel = 801 ,
			maxLevel = 900 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 1 ,
					diff_2_type = "count" ,
					diff_2_value = 2 ,
					diff_3_type = "count" ,
					diff_3_value = 3 ,
					diff_4_type = "count" ,
					diff_4_value = 4 ,
					diff_5_type = "count" ,
					diff_5_value = 5 ,
				} ,
				
			} ,
		} ,

		[5] = {
			minLevel = 901 ,
			maxLevel = 1000 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 0 ,
					diff_2_type = "count" ,
					diff_2_value = 2 ,
					diff_3_type = "count" ,
					diff_3_value = 3 ,
					diff_4_type = "count" ,
					diff_4_value = 4 ,
					diff_5_type = "count" ,
					diff_5_value = 5 ,
				} ,
				
			} ,
		} ,

		[6] = {
			minLevel = 1001 ,
			maxLevel = 1200 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 2 ,
					diff_2_type = "count" ,
					diff_2_value = 3 ,
					diff_3_type = "count" ,
					diff_3_value = 9999 ,
					diff_4_type = "count" ,
					diff_4_value = 4 ,
					diff_5_type = "count" ,
					diff_5_value = 5 ,
				} ,
				
			} ,
		} ,

		[7] = {
			minLevel = 1201 ,
			maxLevel = 1300 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 2 ,
					diff_2_type = "count" ,
					diff_2_value = 3 ,
					diff_3_type = "count" ,
					diff_3_value = 4 ,
					diff_4_type = "count" ,
					diff_4_value = 5 ,
					diff_5_type = "count" ,
					diff_5_value = 6 ,
				} ,
				
			} ,
		} ,

		[8] = {
			minLevel = 1301 ,
			maxLevel = 1600 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 6 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 4 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 7 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 10 ,
				} ,
				[2] = {
					mixDiff = 7 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 7 ,
					diff_2_type = "count" ,
					diff_2_value = 8 ,
					diff_3_type = "count" ,
					diff_3_value = 10 ,
					diff_4_type = "count" ,
					diff_4_value = 13 ,
					diff_5_type = "count" ,
					diff_5_value = 16 ,
				} ,
				
			} ,
		} ,

		[9] = {
			minLevel = 1601 ,
			maxLevel = tonumber( TopLevelDiffTagLogicConfig.maxLevelId - 60) ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 8 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 4 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 7 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 10 ,
				} ,
				[2] = {
					mixDiff = 9 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 9 ,
					diff_2_type = "count" ,
					diff_2_value = 10 ,
					diff_3_type = "count" ,
					diff_3_value = 12 ,
					diff_4_type = "count" ,
					diff_4_value = 15 ,
					diff_5_type = "count" ,
					diff_5_value = 18 ,
				} ,
				
			} ,
		} ,

		[10] = {
			minLevel = tonumber( TopLevelDiffTagLogicConfig.maxLevelId - 60 + 1) ,
			maxLevel = TopLevelDiffTagLogicConfig.maxLevelId ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 10 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 3 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 4 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 6 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 10 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 15 ,
				} ,
				[2] = {
					mixDiff = 11 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 13 ,
					diff_2_type = "count" ,
					diff_2_value = 14 ,
					diff_3_type = "count" ,
					diff_3_value = 16 ,
					diff_4_type = "count" ,
					diff_4_value = 20 ,
					diff_5_type = "count" ,
					diff_5_value = 25 ,
				} ,
				
			} ,
		} ,
		
	}


	TopLevelDiffTagLogicConfig.V701 = table.clone( TopLevelDiffTagLogicConfig.V7 )
	TopLevelDiffTagLogicConfig.V701[4] = {
		minLevel = 801 ,
		maxLevel = 900 ,
		list = {
			[1] = {
				mixDiff = 0 ,
				maxDiff = 9999 ,
				diff_1_type = "count" ,
				diff_1_value = 1 ,
				diff_2_type = "count" ,
				diff_2_value = 2 ,
				diff_3_type = "count" ,
				diff_3_value = 9999 ,
				diff_4_type = "count" ,
				diff_4_value = 3 ,
				diff_5_type = "count" ,
				diff_5_value = 4 ,
			} ,
			
		} ,
	}


	------------------------------------------------------------------------------
	TopLevelDiffTagLogicConfig.V8 = {

		[1] = {
			minLevel = 0 ,
			maxLevel = 100 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 1 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 3 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 4 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 5 ,
				} ,
				[2] = {
					mixDiff = 2 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 1 ,
					diff_2_type = "count" ,
					diff_2_value = 2 ,
					diff_3_type = "count" ,
					diff_3_value = 3 ,
					diff_4_type = "count" ,
					diff_4_value = 4 ,
					diff_5_type = "count" ,
					diff_5_value = 5 ,
				} ,
				
			} ,
		} ,

		[2] = {
			minLevel = 101 ,
			maxLevel = 400 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 0 ,
					diff_2_type = "count" ,
					diff_2_value = 9999 ,
					diff_3_type = "count" ,
					diff_3_value = 1 ,
					diff_4_type = "count" ,
					diff_4_value = 9999 ,
					diff_5_type = "count" ,
					diff_5_value = 2 ,
				} ,
				
			} ,
		} ,

		[3] = {
			minLevel = 401 ,
			maxLevel = 800 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 1 ,
					diff_2_type = "count" ,
					diff_2_value = 9999 ,
					diff_3_type = "count" ,
					diff_3_value = 2 ,
					diff_4_type = "count" ,
					diff_4_value = 3 ,
					diff_5_type = "count" ,
					diff_5_value = 4 ,
				} ,
				
			} ,
		} ,

		[4] = {
			minLevel = 801 ,
			maxLevel = 900 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 1 ,
					diff_2_type = "count" ,
					diff_2_value = 2 ,
					diff_3_type = "count" ,
					diff_3_value = 3 ,
					diff_4_type = "count" ,
					diff_4_value = 4 ,
					diff_5_type = "count" ,
					diff_5_value = 5 ,
				} ,
				
			} ,
		} ,

		[5] = {
			minLevel = 901 ,
			maxLevel = 1000 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 0 ,
					diff_2_type = "count" ,
					diff_2_value = 2 ,
					diff_3_type = "count" ,
					diff_3_value = 3 ,
					diff_4_type = "count" ,
					diff_4_value = 4 ,
					diff_5_type = "count" ,
					diff_5_value = 5 ,
				} ,
				
			} ,
		} ,

		[6] = {
			minLevel = 1001 ,
			maxLevel = 1200 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 2 ,
					diff_2_type = "count" ,
					diff_2_value = 3 ,
					diff_3_type = "count" ,
					diff_3_value = 9999 ,
					diff_4_type = "count" ,
					diff_4_value = 4 ,
					diff_5_type = "count" ,
					diff_5_value = 5 ,
				} ,
				
			} ,
		} ,

		[7] = {
			minLevel = 1201 ,
			maxLevel = 1300 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 2 ,
					diff_2_type = "count" ,
					diff_2_value = 3 ,
					diff_3_type = "count" ,
					diff_3_value = 4 ,
					diff_4_type = "count" ,
					diff_4_value = 5 ,
					diff_5_type = "count" ,
					diff_5_value = 6 ,
				} ,
				
			} ,
		} ,

		[8] = {
			minLevel = 1301 ,
			maxLevel = 1700 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 6 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 4 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 7 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 10 ,
				} ,
				[2] = {
					mixDiff = 7 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 7 ,
					diff_2_type = "count" ,
					diff_2_value = 8 ,
					diff_3_type = "count" ,
					diff_3_value = 10 ,
					diff_4_type = "count" ,
					diff_4_value = 13 ,
					diff_5_type = "count" ,
					diff_5_value = 16 ,
				} ,
				
			} ,
		} ,

		[9] = {
			minLevel = 1701 ,
			maxLevel = 2000 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 10 ,
					diff_2_type = "count" ,
					diff_2_value = 12 ,
					diff_3_type = "count" ,
					diff_3_value = 15 ,
					diff_4_type = "count" ,
					diff_4_value = 18 ,
					diff_5_type = "count" ,
					diff_5_value = 21 ,
				} ,
			} ,
		} ,

		[10] = {
			minLevel = 2001 ,
			maxLevel = 2400 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 13 ,
					diff_2_type = "count" ,
					diff_2_value = 15 ,
					diff_3_type = "count" ,
					diff_3_value = 20 ,
					diff_4_type = "count" ,
					diff_4_value = 23 ,
					diff_5_type = "count" ,
					diff_5_value = 26 ,
				} ,
			} ,
		} ,

		[11] = {
			minLevel = 2401 ,
			maxLevel = 2500 ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 18 ,
					diff_2_type = "count" ,
					diff_2_value = 20 ,
					diff_3_type = "count" ,
					diff_3_value = 25 ,
					diff_4_type = "count" ,
					diff_4_value = 28 ,
					diff_5_type = "count" ,
					diff_5_value = 31 ,
				} ,
			} ,
		} ,

		[12] = {
			minLevel = 2501 ,
			maxLevel = tonumber( TopLevelDiffTagLogicConfig.maxLevelId - 60) ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 8 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 1 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 2 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 4 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 7 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 10 ,
				} ,
				[2] = {
					mixDiff = 9 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 9 ,
					diff_2_type = "count" ,
					diff_2_value = 10 ,
					diff_3_type = "count" ,
					diff_3_value = 12 ,
					diff_4_type = "count" ,
					diff_4_value = 15 ,
					diff_5_type = "count" ,
					diff_5_value = 18 ,
				} ,
				
			} ,
		} ,

		[13] = {
			minLevel = tonumber( TopLevelDiffTagLogicConfig.maxLevelId - 60 + 1) ,
			maxLevel = TopLevelDiffTagLogicConfig.maxLevelId ,
			list = {
				[1] = {
					mixDiff = 0 ,
					maxDiff = 10 ,
					diff_1_type = "diff_plus_count" ,
					diff_1_value = 3 ,
					diff_2_type = "diff_plus_count" ,
					diff_2_value = 4 ,
					diff_3_type = "diff_plus_count" ,
					diff_3_value = 6 ,
					diff_4_type = "diff_plus_count" ,
					diff_4_value = 10 ,
					diff_5_type = "diff_plus_count" ,
					diff_5_value = 15 ,
				} ,
				[2] = {
					mixDiff = 11 ,
					maxDiff = 9999 ,
					diff_1_type = "count" ,
					diff_1_value = 13 ,
					diff_2_type = "count" ,
					diff_2_value = 14 ,
					diff_3_type = "count" ,
					diff_3_value = 16 ,
					diff_4_type = "count" ,
					diff_4_value = 20 ,
					diff_5_type = "count" ,
					diff_5_value = 25 ,
				} ,
				
			} ,
		} ,
		
	}

	TopLevelDiffTagLogicConfig.V801 = table.clone( TopLevelDiffTagLogicConfig.V8 )
	TopLevelDiffTagLogicConfig.V801[4] = {
		minLevel = 801 ,
		maxLevel = 900 ,
		list = {
			[1] = {
				mixDiff = 0 ,
				maxDiff = 9999 ,
				diff_1_type = "count" ,
				diff_1_value = 1 ,
				diff_2_type = "count" ,
				diff_2_value = 2 ,
				diff_3_type = "count" ,
				diff_3_value = 9999 ,
				diff_4_type = "count" ,
				diff_4_value = 3 ,
				diff_5_type = "count" ,
				diff_5_value = 4 ,
			} ,
			
		} ,
	}

	return TopLevelDiffTagLogicConfig

end
